name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install flake8==5.0.4
          pip3 install -r ./vk/api/requirements.txt
          pip3 install -r ./vk/parser/requirements.txt
      - name: Flake8
        run: flake8 .

      - name: Archive html linter results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: linter-result
          path: flake-report